http-party/node-http-proxy

lib/http-proxy/passes/web-incoming.js

The way to detect TLSSockets in node 0.12 and iojs has changed. You can
just check `socket.encrypted` now :)
Fixes #772

fix "x-forwarded-proto" in node 0.12 and iojs

---

lib/http-proxy.js
lib/http-proxy/passes/web-outgoing.js
test/lib-http-proxy-passes-web-outgoing-test.js

* Add support for auto host rewriting and protocol rewriting
* Only rewrite URLs when the redirected host matches the original target

Fixes / additions to URL rewriting

---

lib/http-proxy/common.js
lib/http-proxy/passes/web-incoming.js
lib/http-proxy/passes/ws-incoming.js
test/lib-https-proxy-test.js

With node 0.12.2, `common.getPort` was always returning a default port `80` even for HTTPS connections, because `req.connection.pair` is undefined on this version of node.
Here is a fix, along with some fixes for the HTTPS tests. It has been tested with node 0.10.38 and node 0.12.2 on windows.

Fix default port detection with node 0.12.x

---

README.md

Added missing config options for httpProxy.createProxyServer. Updated to include all options listed in `lib/http-proxy.js`
Addresses nodejitsu/node-http-proxy#851

Added missing configuration options

---

UPGRADING.md

Recently ran into a case where I had to upgrade the `http-proxy` version for an app, and that app was using a proxy table.
I'm not sure how many users are still using the 0.x.x version of `http-proxy`, but the added link (found from one of the GH issues) may encourage them to switch over to 1.x.x if they were using the old version due to its proxy table support and the activation energy to upgrade was too high.
Edit: There was some work involved in creating a proxy table to map paths to urls, disregarding the source's hostname, so I'm not sure if this would warrant creating a module (w/ source hostname support). Here's the relevant code if you also want to add it to the README:
```
for (var pathPrefix in proxyTable) {
if (proxyTable.hasOwnProperty(pathPrefix)) {
if …
```

Updating the upgrading doc

---

lib/http-proxy/common.js
test/lib-http-proxy-common-test.js

Previously, if target='http://localhost:9060/appEndpoint' and req.url='', the url the proxied request will hit is: 'http://localhost:9060/appEndpoint**/**'
With the change, if target='http://localhost:9060/appEndpoint' and req.url='', the url the proxied request will hit is: 'http://localhost:9060/appEndpoint'
This is helpful if the app endpoint is to a router that is sensitive to the trailing slash (e.g., a Rails router)

Removed unspecified trailing slash in proxy url

---

package.json

npm v3 tries to dedupe the dependencies by default, and keeping dependencies up-to-date helps better deduplication.
And [`requires-port`](https://github.com/unshiftio/requires-port) v1.0.0 includes a small but important fix. https://github.com/unshiftio/requires-port/pull/2

Bump requires-port, server and ws

---

README.md

Added TOC to README and moved some stuff around/added some minor comments. See diff for details.

More structured readme

---

README.md
lib/http-proxy/common.js
test/lib-http-proxy-common-test.js

When using option ignorePath common.js would set target to '/'.
This would break requests in cases where this slash was unwanted, for instance when fetching files, or in some cases when using GET parameters.

Fix for #839 (Ignore path and the trailing slash)

---

lib/http-proxy/common.js
test/lib-http-proxy-common-test.js

Shrunk replace options.
Fix https://github.com/nodejitsu/node-http-proxy/issues/946.

fix(common) urlJoin replace: ":/" -> "http?s:/"

---

package.json

This PR switches `npm test` to using the default mocha reporter. The "landing" reporter doesn't render well on CI servers like TravisCI.

mocha: Use default reporter

---

README.md

README example implies request instead of response parameter

#949 Proxy example using req instead res on README

---

README.md

Document the option: "headers", as seen in existing example:
https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/proxy-http-to-https.js
This options will add provided map of headers to requests to target.

Fixed missing documentation: #options.headers

---

lib/http-proxy/passes/web-incoming.js

Reasoning: Rack's request class [makes use of](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L243) this HTTP header. Certain edge-case scenarios (proxying from ember-cli to a Rails backend) can be problematic without this header being present.
/cc @perlun, @jesjos

Set the x-forwarded-host flag when xfwd is enabled

---

README.md

Fix formatting of the `headers` option

---

test/lib-http-proxy-test.js

One test "`should emit open and close events when socket.io client connects and disconnects`" is broken since socket.io-client upgraded to 1.4.6 (upgrading its dependency engine.io-client to 1.6.9), because of a new default value in commit: socketio/engine.io-client@7fa16d531b40fb316e418e8f3d9e50bb07b38531
This pull request force the value of `rejectUnauthorized` to null (like before upgrade) to fix the test.

Fix tests for node 0.10 + socket.io-client@1.4.6 (engine.io-client@1.6.9)

---

lib/http-proxy/passes/web-incoming.js
test/lib-http-proxy-passes-web-incoming-test.js

Hello folks, 
This is my first contribution, if there is anything wrong with my PR, please let me know.
We've been using node-http-proxy in our prod server since 3 years now and its working as a charm (thank you!), but everyday we got our log files full of `socket hang up` messages, so I come here dig code and found an issue for that: #[813](https://github.com/nodejitsu/node-http-proxy/issues/813). 
To me, this looks like a bug also, we should not send as an error a disconnection between the client, so I made this PR using the info in the issue.
I'm not sure if emit a `disconnected` event is the best approach, or if you guys want something more elaborate for that. Please, let me know your thoughts.

Emit disconnected event instead of error when ECONNRESET

---

lib/http-proxy/common.js

While using secure: true for proxy connections, there is no way to pass the trusted root CA(s) or intermediate CA(s). This change allows that to be passed in the httpProxy createServer options and used for the outgoing proxy connection.

#866 Copy CA from options into outbound proxy

---

README.md
lib/http-proxy/passes/web-outgoing.js
test/lib-http-proxy-passes-web-outgoing-test.js

Implement rewriting of the location header for responses with status code 201, according to RFC2616 section 10.2.2, in response to issue #914

Location header rewriting for responses with status 201

---

examples/middleware/bodyDecoder-middleware.js

Support for bodyparser.json and bodyparser.urlencoded.
Fixes #955 #843 #791

[Fix] bodyparser example - restream body before proxying

---

README.md
lib/http-proxy/common.js
lib/http-proxy/passes/web-outgoing.js
test/lib-http-proxy-passes-web-outgoing-test.js

Sometime the `set-cookie` header specify a domain for the cookie. When proxying the a target using `changeOrigin` option, the response may contain a cookie not matching the domain of the client.
Example of such a cookie: `foo=bar; domain=my.domain; expires=Tue, 12-Feb-2019 10:50:41 GMT; path=/`
This pull request adds an option to rewrite the `set-cookie` header of the response.
Possible option values:
- disabled (default): `cookieDomainRewrite: false`
- rewrite all domains: `cookieDomainRewrite: "my.client.domain"`
- remove all domains: `cookieDomainRewrite: ""`
- more advanced configuration (this example removes all except one):
```
cookieDomainRewrite: {
"*": "",
"some.domain": "some.domain"
}
```
Let me know if I can improve this option or for any question.

Add option to rewrite domain in set-cookie headers

---

lib/http-proxy/passes/web-outgoing.js

Calling res.writeHead has the side effect of setting the Reason-Phrase back to node defaults regardless of what is in the response status line.  I'm using Reason-Phrase codes to sub-route api responses and they were all being reset.  This change only sets the statusMessage (Reason-Phrase) if it exists on the proxyRes and is successfully passing it through in my tests.
from [docs](https://nodejs.org/api/http.html#http_response_statusmessage):
So if just calling writeHead and not passing the optional statusMessage second argument, I believe it is getting reset to undefined and then defaulting it. I'm not sure if there is a good reason for using writeHead in general here since it seems like setting statusCode / statusMessage properties directly accomplishes the same with less side effects, …

Fix for Reason-Phrase being overwritten on proxy response.

---

lib/http-proxy/passes/web-incoming.js
test/lib-http-proxy-test.js

When tools like HAProxy run health checks they don't supply http Host header,
which makes http-proxy to crash, pretty unfortunate side-effect for a health check. :)

Made it not to crash with omited Host http header

---

lib/http-proxy/passes/web-outgoing.js

This re-adds the call to writeHead in [web-outgoing](/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-outgoing.js#L110) so that other middleware which depend on or patch the response.writeHead method (such as [harmon](/No9/harmon)) don't break.
Depends on No9/harmon#38 being accepted

Properly write response header optionally including statusMessage

---

README.md

http-proxy provides a [proxyTimeout option](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-incoming.js#L122) that allows us to set a timeout on the outgoing socket connection to the target. This timeout is very effective when the upstream target does not respond within an expected time.
I had wasted a few hours searching for this option. Documenting this option can save others a significant amount of time.

Add proxy-timeout option to documentation

---

lib/http-proxy/passes/web-outgoing.js
test/lib-http-proxy-passes-web-outgoing-test.js

when using with 'http2', http2 throws an error 'can't set deprecated header : connection'

not setting 'connection' header in case of http2

---

lib/http-proxy/passes/web-incoming.js
test/lib-http-proxy-passes-web-incoming-test.js

Errors in forward requests were not handled. This caused my process to exit after an `ECONNREFUSED`.
Errors in target request and the original request were already properly handled. I added forward request error handling the same way.
Added a test case proving the fix.

Handle errors for forward request

---

lib/http-proxy/passes/web-outgoing.js
test/lib-http-proxy-passes-web-outgoing-test.js
test/lib-http-proxy-test.js

This PR fixes the issue https://github.com/nodejitsu/node-http-proxy/issues/1029
In RFC, HTTP header key is case-insensitive (ref: https://github.com/nodejs/node-v0.x-archive/issues/1954).
But, proxy server should care not to change the original request unintentionally ✨

Keep original letter case of response header keys

---

lib/http-proxy/passes/web-incoming.js

In my merged PR #1099, I was too fast. I didn't make enough changes in the error handler and for `ECONNREFUSED` this introduced a new error, since `proxyReq` was not defined.
To fix it, I wrapped the error handler in a `createErrorHandler()` function to specify which request should be handled (`proxyReq` or `forwardReq`).

Fix newly introduced error in handler for forward ECONNREFUSED

---

README.md
lib/http-proxy.js
lib/http-proxy/passes/web-outgoing.js
test/lib-http-proxy-passes-web-outgoing-test.js
test/lib-http-proxy-test.js

My change (#1098) has side effect because of the header values of `rawHeaders` are not always same with the values of `headers`. ( #1101, #1102, #1103) 🙇 
This PR includes these changes to solve it:
1. Overwrite only key, not value.
2. Overwrite key if raw header key is available.
3. Add `preserveHeaderKeyCase` option (default: false).
@jcrugzz  I'd like to hear your thought. 🍣 
I have to add specs before marge this.
Sorry for any inconvenience, and thanks to all.

[WIP] Revert default behavior of writeHeaders method

---

package.json

`node-http-proxy` is not affected by the only breaking change in version [2.0.0](https://github.com/primus/eventemitter3/releases/tag/2.0.0) so I think it makes sense to update as there are some nice performance improvements.

Update eventemitter3 to version 2.0.x

---

lib/http-proxy/index.js
test/lib-http-proxy-passes-web-incoming-test.js

Global options are being overwritten from `proxy.web(req, res, opts)`, which breaks some more complex scenarios like proxying to multiple servers with different options.
This is essentially the same as https://github.com/nodejitsu/node-http-proxy/pull/833 but with a test case.

Fix overwriting of global options

---

examples/middleware/bodyDecoder-middleware.js

Restream body before proxying, fix to support for Content-Type of  application/x-www-form-urlencoded.
#955 #843 #1027

[Fix] bodyparser example - support for Content-Type of  application/x-www-form-urlencoded

---

lib/http-proxy.js

Updates options documentation for location rewrite to include 201 responses. See #1024

Fix docs for rewrite options - 201 also handled

---

lib/http-proxy/passes/web-incoming.js

Let's consider a scenario
`proxy (Internet-facing) -> proxy(load balancer) -> application` where both proxies will be based on node-http-proxy, **with current logic original host to be lost**
With updated logic the original forwarded host will be passed down the proxy chain

x-forwarded-host overwrite for mutli level proxies

---

examples/middleware/modifyResponse-middleware.js

This PR simply fixes the modifyResponse-middleware example to work properly by removing a deprecated function call (connect.createServer()) and passing the middleware functions to an http server.

Fix modify response middleware example

---

examples/http/reverse-proxy.js

If we set `target:req.url`, request to http://localhost/favicon.ico would be mapped to  http://localhost/favicon.ico/favicon.ico
This PR changes `target` to make it equal destination host authority

Fix incorrect target name for reverse proxy example

---

README.md

fix 'Modify Response' readme section to avoid unnecessary array copying

---

lib/http-proxy/passes/web-incoming.js
test/lib-http-proxy-passes-web-incoming-test.js

Hotfix for https://www.npmjs.com/advisories/1486
Expecting build error due to Node 6.  Waiting for https://github.com/http-party/node-http-proxy/pull/1397  to be merged to have a clean CI build.

Skip sending the proxyReq event when the expect header is present
